name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]
        node-version: ["22"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install package (editable)
        run: python -m pip install -e .

      - name: Generate golden outputs
        run: python tools/gen_golden.py

      - name: Run golden tests
        run: python tests/golden.py
